# This is a basic workflow to help you get started with Actions

name: Build & Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'resources/**'
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'resources/**'
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java-version: [ 8, 11, 16 ]
        java-distribution: [ adopt, adopt-openj9 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Setup Java Version
        uses: actions/setup-java@v3.14.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
          architecture: x64
          cache: 'maven'

      # Runs a single command using the runners shell
      - name: Build with Maven
        run: mvn clean package 
