name: License checker

on:
  push:
    branches:
      - maste
    paths-ignore:
      - 'doc/**'
      - 'resources/**'
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - 'resources/**'
      - '**.md'

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check License Header
        uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff
